Added retry decorator to get_roi_df function
vandersat/vds-api-client pull request #41
Opened 2021-04-21 17:26 UTC by sshoaie

2021-04-22 09:01 UTC, teije01 requested changes
If you could add a timeout, and only retry on the expected error than that would greatly enhance the user's experience. Currently, if you make a small error in the request, you have to wait a very long time for the error to show. Perhaps we can also decrease the amount of attempts to 3 here.

2021-04-22 09:01 UTC, teije01 commented on vds_api_client/api_v2.py
> +           stop_max_attempt_number=7)
I think it would be best if we would add a `timeout=10` to the get request, and only retry when the connection timeout error occurs. There is the `retry_on_exception` argument for that in the retry decorator. It expects a function that returns a boolean indicating if the first argument is the error you want to retry. See the `_uuid_status` method for an example.

The reason for this is that otherwise we start retrying also the requests for which different errors occur like the ones where the user has not enough privileges for a request.

2021-04-22 11:17 UTC, sshoaie commented on vds_api_client/api_v2.py
> +           stop_max_attempt_number=7)
Ok I will incorporate these.

2021-05-20 18:12 UTC, teije01 commented on vds_api_client/api_v2.py
> +           stop_max_attempt_number=7)
do you still want to implement this? If it takes you too much time, I can do it myself

2021-05-20 20:55 UTC, sshoaie commented on vds_api_client/api_v2.py
> +           stop_max_attempt_number=7)
Thanks, that would be appreciated.

2021-05-21 09:11 UTC, teije01 approved these changes

2021-05-21 09:15 UTC, merged

2021-05-21 10:36 UTC, sshoaie commented
Lekker bezig!